name: corona_apps
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  sliding_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/image/coronaVirusGreen.png
    - asset/image/coronaVirusYellow.png
    - asset/image/indo.png
    - asset/image/kematian.png
    - asset/image/sembuh.png
    - asset/image/headerHome.png
    - asset/image/beritaCovid.jpg
    - asset/image/beritaUpdateCovid.jpg
    - asset/image/beritaVaksin.jpg
    - asset/image/beritaWHO.jpg
    - asset/image/headerKasus.png
    - asset/image/backgroundKasusTerbanyak.png
    - asset/image/phoneIcon.png
    - asset/image/phoneGreen.png
    - asset/image/edukasi1.png
    - asset/image/edukasi2.png
    - asset/image/edukasi3.png
    - asset/image/edukasi4.png
    - asset/image/edukasi5.png
    - asset/image/motivasi1.png
    - asset/image/tesCovidImage.png
    - asset/image/coronaVirusWhite.png
    - asset/image/resikoRendah.png
    - asset/image/headerHasil.png
    - asset/image/vaksinBanner.png
    - asset/image/hasilRentan.png
    - asset/image/hasilResikoRendah.png
    - asset/image/hasilSangatBeresiko.png
    - asset/image/hasilWaspada.png
    - asset/image/onBoarding1.png
    - asset/image/onBoardingFooter.png
    - asset/image/onBoarding2.png
    - asset/image/onBoarding3.png
    - asset/image/unknownUser.png
    - asset/image/googleIcon.png
    - asset/image/faceBookIcon.png

  fonts:
    - family: NunitoBlack
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Black.ttf
    - family: NunitoBlackItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-BlackItalic.ttf
    - family: NunitoBold
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Bold.ttf
    - family: NunitoBoldItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-BoldItalic.ttf
    - family: NunitoExtraBold
      fonts:
        - asset: asset/fonts/Nunito/Nunito-ExtraBold.ttf
    - family: NunitoExtraBoldItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
    - family: NunitoExtraLight
      fonts:
        - asset: asset/fonts/Nunito/Nunito-ExtraLight.ttf
    - family: NunitoExtraLightItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-ExtraLightItalic.ttf
    - family: NunitoItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Italic.ttf
    - family: NunitoLight
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Light.ttf
    - family: NunitoLightItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-lightItalic.ttf
    - family: NunitoRegular
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Regular.ttf
    - family: NunitoSemiBold
      fonts:
        - asset: asset/fonts/Nunito/Nunito-Semibold.ttf
    - family: NunitoSemiBoldItalic
      fonts:
        - asset: asset/fonts/Nunito/Nunito-SemiBoldItalic.ttf