name: corona_apps
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  sliding_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/image/coronaVirusGreen.png
    - asset/image/coronaVirusYellow.png
    - asset/image/indo.png
    - asset/image/kematian.png
    - asset/image/sembuh.png
    - asset/image/headerHome.png
    - asset/image/beritaCovid.jpg
    - asset/image/beritaUpdateCovid.jpg
    - asset/image/beritaVaksin.jpg
    - asset/image/beritaWHO.jpg
    - asset/image/headerKasus.png
    - asset/image/backgroundKasusTerbanyak.png
    - asset/image/phoneIcon.png
    - asset/image/phoneGreen.png
    - asset/image/edukasi1.png
    - asset/image/edukasi2.png
    - asset/image/edukasi3.png
    - asset/image/edukasi4.png
    - asset/image/edukasi5.png
    - asset/image/motivasi1.png
    - asset/image/tesCovidImage.png
    - asset/image/coronaVirusWhite.png